export enum AgentState {
  IDLE = 'IDLE',
  THINKING = 'THINKING',
  SEARCHING = 'SEARCHING',
  WAITING_PERMISSION = 'WAITING_PERMISSION',
  WORKING = 'WORKING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS'
}
